# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datamhs.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import mesh as mesh
from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from datamhs import*


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.koneksi()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 501, 541))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Gracia Rizka Pasfica/Pictures/unnamed.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Rancho")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 481, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 360, 54, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 400, 54, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 440, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 480, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 360, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 400, 371, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 440, 371, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 480, 371, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 510, 82, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 510, 82, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 510, 82, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 510, 82, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.datamhs.btnEdit.clicked.connect(self.edit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "DATA MAHASISWA"))
        self.label_3.setText(_translate("MainWindow", "NIM"))
        self.label_4.setText(_translate("MainWindow", "NAMA"))
        self.label_5.setText(_translate("MainWindow", "JURUSAN"))
        self.label_6.setText(_translate("MainWindow", "NO. TELP"))
        self.pushButton.setText(_translate("MainWindow", "TAMBAH"))
        self.pushButton_2.setText(_translate("MainWindow", "EDIT"))
        self.pushButton_3.setText(_translate("MainWindow", "CLEAR"))
        self.pushButton_4.setText(_translate("MainWindow", "HAPUS"))
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.btnLogin.clicked.connect(self.login)

    def koneksi(self):
            con = pymysql.connect(db = 'db_mhs', user = 'root', passwd = '', host = 'localhost', port = 3306, autocommit = True)
            cur = con.cursor()
            if(cur):
                self.messageBox("Koneksi", "Koneksi Berhasil")
            else:
                self.messageBox("Koneksi", "Koneksi Gagal")

    def messagebox(self, title, message) :
        mesh = QtWidgets.QMessageBox()
        mesh.setWindowTitle(title)
        mesh.setText(message)

    mesh.setStandardButtons(QtWidgets.QMessageBox.Ok)
    mesh.exec_()

    def submit(self):
        nim = self.txtNim.text()
        nama = self.txtNama.text()
        jurusan = self.txtJurusan.text()
        no = self.txtNo.text()
        insert = (nim, nama, jurusan, no)
        print(insert)
        if self.txtNIM.text() and self.txtNama.text() and self.txtJurusan.text() and self.txtNo.text():
            con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost',port=3306, autocommit=True)
            cur = con.cursor()
            sql = "INSERT INTO mhs(nim, nama, jurusan, no)" + "VALUES"+ str(insert)
            data = cur.execute(sql)
            self.messagebox("SUKSES", "Data Berhasil di Submit")
        else:
            self.messagebox("GAGAL", "Mohon lengkapi form ")
class datamhs(QtWidgets):
    def __init__(self):
        super(self).__init__()
        self.datamhs = Ui_datamhs()
        self.datamhs.setupUi(self)

class Ui_datamhs(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

    def submit(self):
        nim = self.datamhs.txtNim_2.text()
        nama = self.datamhs.txtNama_2.text()
        jurusan = self.datamhs.txtJurusan_2.text()
        no = self.datamhs.txtNo_2.text()
        insert = (nim, nama, jurusan, no)
        print(insert)
        if self.datamhs.txtNim_2.text() and self.datamhs.txtNama_2.text() and self.datamhs.txtJurusan_2.text() and self.datamhs.txtNo_2.text():
            135
            con = pymysql.connect(db='db_mhs',user='root', passwd='', host='localhost', port=3306,autocommit=True)
            cur = con.cursor()
            sql = "INSERT INTO mhs(nim, nama, jurusan, no)" + " VALUES "+ str(insert)
            data = cur.execute(sql)
            Ui_MainWindow.messagebox(Ui_MainWindow, "SUKSES", "Data Berhasil di Submit")
        else:
            Ui_MainWindow.messagebox(Ui_MainWindow, "GAGAL", "Mohon lengkapi form ")

class Ui_MainWindow():
    def login(self):
        uname = self.txtUname.text()
        pw = self.txtPass.text()
        con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "SELECT * from admin where uname=%s and pw = % s"
        data = cur.execute(sql, (uname, pw))
        if (len(cur.fetchall()) > 0):
            self.form = datamhs()
            self.form.show()
        else:
            self.messagebox("GAGAL", "Username atau Password Salah ! ")

    def edit(self):
        nim = self.datamhs.txtNim_2.text()
        nama = self.datamhs.txtNama_2.text()
        jurusan = self.datamhs.txtJurusan_2.text()
        no = self.datamhs.txtNo_2.text()
        insert = (nim, nama, jurusan, no)
        if self.datamhs.txtNim_2.text() and self.datamhs.txtNama_2.text() and self.datamhs.txtJurusan_2.text() and self.datamhs.txtNo_2.text():
            con = pymysql.connect(db='tubes_gui', user='root', passwd='', host='localhost', port=3306, autocommit=True)
            cur = con.cursor()
            sql = "UPDATE mhs set nama='" + str(nama) +"', jurusan='" + str(jurusan) + "', no='" + str(no)+ "' where nim='" + str(nim) + "'" data = cur.execute(sql)
            Ui_MainWindow.messagebox(Ui_MainWindow, "SUKSES", "Data Berhasil di Submit")
        else:
            Ui_MainWindow.messagebox(Ui_MainWindow, "GAGAL", "Mohon lengkapi form ")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
